//LOCALHOST
GET http://localhost:3000   
###
GET http://localhost:3000/username

###
GET http://localhost:3000/644ae96e2388fbfbcd46c5c1
###

GET http://localhost:3000/644ae96e2388fbfbcd46c5c2
###

GET http://localhost:3000/644ae96e2388fbfbcd46c5c3



###
POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "firstName": "Paige",
    "lastName": "Engler",
    "email": "p@test.com",
    "favoriteColor": "aqua",
    "birthday": "January 11th, 2018"
  }

###
PUT http://localhost:3000/645538fec5a41679734a56d9 HTTP/1.1
content-type: application/json

{
    "firstName": "Paige",
    "lastName": "Engler",
    "email": "Paige@test.com",
    "favoriteColor": "Aqua Marine",
    "birthday": "July 11th, 2020"
  }

###
DELETE http://localhost:3000/645538fec5a41679734a56d9 HTTP/1.1
content-type: application/json


//PRODUCTION
###
GET https://cse341-c07f.onrender.com 
###
GET https://cse341-c07f.onrender.com/username

###
GET https://cse341-c07f.onrender.com/644ae96e2388fbfbcd46c5c1
###

GET https://cse341-c07f.onrender.com/644ae96e2388fbfbcd46c5c2
###

GET https://cse341-c07f.onrender.com/644ae96e2388fbfbcd46c5c3




###
POST https://cse341-c07f.onrender.com/contact HTTP/1.1
content-type: application/json

{
    "firstName": "Paige",
    "lastName": "Engler",
    "email": "p@test.com",
    "favoriteColor": "aqua",
    "birthday": "January 11th, 2018"
  }

###
PUT https://cse341-c07f.onrender.com/6455e0d2f8c286fa723abd1b HTTP/1.1
content-type: application/json

{
    "firstName": "Paige",
    "lastName": "Engler",
    "email": "Paige@test.com",
    "favoriteColor": "Aqua Marine",
    "birthday": "July 11th, 2020"
  }

###
DELETE https://cse341-c07f.onrender.com/6455768e7c51fdcc36a09e79 HTTP/1.1
content-type: application/json